### ISSUE TITLE
Link for overview not working

### ISSUE THREAD

**Issue by Geobusteni** [krszwsk/asus-x55vd-hackintosh#1]
Hey there,
thank you for the entire library. I was wondering how did you do it?
I am seeing the overview link from readme is not working.
Did you use Clover app for this? Thank you for any bits of info you can deliver!

**Comment by xkrsz** [comment]
Hi, I did that a long time ago and was worried that I wouldn't be able to provide you with any information. Fortunately, I commited the guide a while back, it is now recovered, go ahead and take a look at the current `master` branch.

Feel free to shoot me with any questions, although I may be unable to answer them, as my memory fails me in that regard
